CC=g++

LIBFLAG=-Iinclude -Llib -Isrc -Isrc/components -Isrc/utils -Isrc/systems
FLAGS=-lmingw32 -lglfw3 -lopengl32 -lkernel32 -luser32 -lgdi32 -lcomdlg32

TARGET=game.exe


all: 
	$(CC) $(LIBFLAG) -o game.exe src/*.cpp src/systems/*.cpp src/utils/*.cpp src/glad/*.c  $(FLAGS)
clean:
	rm -f $(TARGET)